// ignore_for_file: avoid_print
import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import '../data/metal_rates.dart';
import 'web_fetch_stub.dart' if (dart.library.html) 'web_fetch_web.dart' as web_fetch;

class MetalRatesService {
  static const String cacheFileName = 'metal_rates_cache.json';

  // Load rates: either from local cache file/web storage, or if not present, from compiled liveMetalRates constant
  static Map<String, dynamic> loadRates() {
    if (kIsWeb) {
      try {
        final webData = web_fetch.loadWebCache();
        if (webData != null) {
          return webData;
        }
      } catch (e) {
        print("Error reading web cache: $e");
      }
      return liveMetalRates;
    }
    try {
      final file = File(cacheFileName);
      if (file.existsSync()) {
        final content = file.readAsStringSync();
        final data = jsonDecode(content);
        if (data is Map<String, dynamic> && data.containsKey('gold24k')) {
          return data;
        }
      }
    } catch (e) {
      print("Error reading metal rates cache: $e");
    }
    return liveMetalRates;
  }

  // Save rates manually to cache
  static Future<void> saveRates(Map<String, dynamic> rates) async {
    final updatedRates = {
      ...rates,
      "lastUpdated": DateTime.now().toUtc().toIso8601String(),
      "status": "success"
    };

    if (kIsWeb) {
      try {
        await web_fetch.saveWebCache(updatedRates);
      } catch (e) {
        print("Error saving web cache: $e");
      }
      return;
    }

    try {
      final file = File(cacheFileName);
      file.writeAsStringSync(jsonEncode(updatedRates));
      print("Metal rates successfully saved to: ${file.path}");
    } catch (e) {
      print("Failed to save runtime cache file: $e");
    }

    // Also write back to lib/data/metal_rates.dart so compile-time references update during development
    try {
      final devFile = File("lib/data/metal_rates.dart");
      final dartContent = '''
// GENERATED FILE - DO NOT MODIFY BY HAND
// Generated by MetalRatesService

const Map<String, dynamic> liveMetalRates = {
  "gold24k": ${updatedRates['gold24k']},
  "gold22k": ${updatedRates['gold22k']},
  "gold18k": ${updatedRates['gold18k']},
  "silver": ${updatedRates['silver']},
  "lastUpdated": "${updatedRates['lastUpdated']}",
  "status": "${updatedRates['status']}"
};
''';
      devFile.writeAsStringSync(dartContent);
      print("Metal rates compile-time file updated.");
    } catch (e) {
      print("Failed to save compile-time file: $e");
    }
  }
}
