// GENERATED FILE - DO NOT MODIFY BY HAND
// Generated by MetalRatesService

const Map<String, dynamic> liveMetalRates = {
  "gold24k": 14608.0,
  "gold22k": 13390.0,
  "gold18k": 10956.0,
  "silver": 250.0,
  "lastUpdated": "2026-06-21T09:39:51.942830Z",
  "status": "success"
};
